# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "john-hancock"
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brandon Turner"]
  s.date = "2012-01-25"
  s.description = "Extendable library for signing and verifying url/request signatures"
  s.email = "bturner@bltweb.net"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "john-hancock.gemspec",
    "lib/john-hancock.rb",
    "lib/john-hancock/request_proxy.rb",
    "lib/john-hancock/request_proxy/base.rb",
    "lib/john-hancock/request_proxy/headers.rb",
    "lib/john-hancock/request_proxy/net_httprequest.rb",
    "lib/john-hancock/request_proxy/rack_request.rb",
    "lib/john-hancock/request_proxy/uri.rb",
    "lib/john-hancock/signature.rb",
    "lib/john-hancock/signature/advanced.rb",
    "lib/john-hancock/signature/base.rb",
    "lib/john-hancock/signature/ec2.rb",
    "lib/john-hancock/signature/oauth.rb",
    "lib/john-hancock/signature/simple.rb",
    "spec/mock/request.rb",
    "spec/mock/request_proxy/mock_request.rb",
    "spec/mock/signature/mock_signature.rb",
    "spec/request_proxy/base_spec.rb",
    "spec/request_proxy/net_httprequest_spec.rb",
    "spec/request_proxy/rack_request_spec.rb",
    "spec/request_proxy/uri_spec.rb",
    "spec/request_proxy_spec.rb",
    "spec/signature/base_spec.rb",
    "spec/signature/simple_spec.rb",
    "spec/signature_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/thinkwell/john-hancock"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Library for signing and verifying url signatures"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.1.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
    else
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.1.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
    end
  else
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.1.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
  end
end

